In [1]:
# importing the libraries
import pandas as pd
import numpy as np

In [2]:
pwd

'C:\\Users\\hi\\Documents\\Artificial Intelligence'

In [3]:
a=pd.read_csv(r"C:\Users\hi\Downloads\matches2008-2016.csv")

In [6]:
print(a.head())

  match_id  season        city        date team1_id team2_id toss_winner  \
0   2008_1    2008   Bangalore  18-04-2008      KKR      RCB         RCB
1   2008_2    2008  Chandigarh  19-04-2008      CSK      KXI         CSK
2   2008_3    2008       Delhi  19-04-2008       RR       DD          RR
3   2008_4    2008      Mumbai  20-04-2008       MI      RCB          MI
4   2008_5    2008     Kolkata  20-04-2008       DC      KKR          DC

  toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0         field  normal           0    KKR          140               0
1           bat  normal           0    CSK           33               0
2           bat  normal           0     DD            0               9
3           bat  normal           0    RCB            0               5
4           bat  normal           0    KKR            0               5

    player_of_match  player_of_match_id  \
0  Brendon McCullum                82.0
1    Michael Hussey                18.0
2  Farveez Maharoof                60.0
3      Mark Boucher               145.0
4      David Hussey                80.0

                                               venue  venue_id    umpire1  \
0         M.Chinnaswamy Stadium Bengaluru, Karnataka         7  Asad Rauf
1  I.S. Bindra Punjab Cricket Association Stadium...         9  MR Benson
2                    Feroz Shah Kotla Stadium, Delhi         2  Aleem Dar
3              Wankhede Stadium, Mumbai, Maharashtra         1   SJ Davis
4          Eden Garden Stadium, Kolkata, West Bengal         3  BF Bowden

          umpire2
0     RE Koertzen
1      SL Shastri
2  GA Pratapkumar
3       DJ Harper
4     K Hariharan

In [7]:
print(a.tail())

    match_id  season       city        date team1_id team2_id toss_winner  \
572  2016_56    2016     Raipur  22-05-2016       DD      RCB         RCB
573  2016_57    2016  Bangalore  24-05-2016       GL      RCB         RCB
574  2016_58    2016      Delhi  25-05-2016      SRH      KKR         KKR
575  2016_59    2016      Delhi  27-05-2016       GL      SRH         SRH
576  2016_60    2016  Bangalore  29-05-2016      SRH      RCB         SRH

    toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
572         field  normal           0    RCB            0               6
573         field  normal           0    RCB            0               4
574         field  normal           0    SRH           22               0
575         field  normal           0    SRH            0               4
576           bat  normal           0    SRH            8               0

      player_of_match  player_of_match_id  \
572       Virat Kohli               149.0
573    AB De Villiers                47.0
574  Moises Henriques               212.0
575      David Warner               207.0
576       Ben Cutting               526.0

                                                venue  venue_id  \
572  Shaheed Veer Narayan Singh International Stadium        27
573        M.Chinnaswamy Stadium Bengaluru, Karnataka         7
574                   Feroz Shah Kotla Stadium, Delhi         2
575                   Feroz Shah Kotla Stadium, Delhi         2
576        M.Chinnaswamy Stadium Bengaluru, Karnataka         7

             umpire1          umpire2
572   A Nand Kishore     BNJ Oxenford
573     AK Chaudhary  HDPK Dharmasena
574        M Erasmus    C Shamshuddin
575        M Erasmus        CK Nandan
576  HDPK Dharmasena     BNJ Oxenford

In [8]:
a.shape

(577, 19)

In [10]:
a.columns

Index(['match_id', 'season', 'city', 'date', 'team1_id', 'team2_id',
       'toss_winner', 'toss_decision', 'result', 'dl_applied', 'winner',
       'win_by_runs', 'win_by_wickets', 'player_of_match',
       'player_of_match_id', 'venue', 'venue_id', 'umpire1', 'umpire2'],
      dtype='object')

In [13]:
type(a)

pandas.core.frame.DataFrame

In [14]:
a.dtypes

match_id               object
season                  int64
city                   object
date                   object
team1_id               object
team2_id               object
toss_winner            object
toss_decision          object
result                 object
dl_applied              int64
winner                 object
win_by_runs             int64
win_by_wickets          int64
player_of_match        object
player_of_match_id    float64
venue                  object
venue_id                int64
umpire1                object
umpire2                object
dtype: object

In [15]:
a.ndim

2

In [16]:
a.size

10963

In [18]:
a.isna

<bound method DataFrame.isna of     match_id  season        city        date team1_id team2_id toss_winner  \
0     2008_1    2008   Bangalore  18-04-2008      KKR      RCB         RCB
1     2008_2    2008  Chandigarh  19-04-2008      CSK      KXI         CSK
2     2008_3    2008       Delhi  19-04-2008       RR       DD          RR
3     2008_4    2008      Mumbai  20-04-2008       MI      RCB          MI
4     2008_5    2008     Kolkata  20-04-2008       DC      KKR          DC
..       ...     ...         ...         ...      ...      ...         ...
572  2016_56    2016      Raipur  22-05-2016       DD      RCB         RCB
573  2016_57    2016   Bangalore  24-05-2016       GL      RCB         RCB
574  2016_58    2016       Delhi  25-05-2016      SRH      KKR         KKR
575  2016_59    2016       Delhi  27-05-2016       GL      SRH         SRH
576  2016_60    2016   Bangalore  29-05-2016      SRH      RCB         SRH

    toss_decision  result  dl_applied winner  win_by_runs  win_by_wickets  \
0           field  normal           0    KKR          140               0
1             bat  normal           0    CSK           33               0
2             bat  normal           0     DD            0               9
3             bat  normal           0    RCB            0               5
4             bat  normal           0    KKR            0               5
..            ...     ...         ...    ...          ...             ...
572         field  normal           0    RCB            0               6
573         field  normal           0    RCB            0               4
574         field  normal           0    SRH           22               0
575         field  normal           0    SRH            0               4
576           bat  normal           0    SRH            8               0

      player_of_match  player_of_match_id  \
0    Brendon McCullum                82.0
1      Michael Hussey                18.0
2    Farveez Maharoof                60.0
3        Mark Boucher               145.0
4        David Hussey                80.0
..                ...                 ...
572       Virat Kohli               149.0
573    AB De Villiers                47.0
574  Moises Henriques               212.0
575      David Warner               207.0
576       Ben Cutting               526.0

                                                 venue  venue_id  \
0           M.Chinnaswamy Stadium Bengaluru, Karnataka         7
1    I.S. Bindra Punjab Cricket Association Stadium...         9
2                      Feroz Shah Kotla Stadium, Delhi         2
3                Wankhede Stadium, Mumbai, Maharashtra         1
4            Eden Garden Stadium, Kolkata, West Bengal         3
..                                                 ...       ...
572   Shaheed Veer Narayan Singh International Stadium        27
573         M.Chinnaswamy Stadium Bengaluru, Karnataka         7
574                    Feroz Shah Kotla Stadium, Delhi         2
575                    Feroz Shah Kotla Stadium, Delhi         2
576         M.Chinnaswamy Stadium Bengaluru, Karnataka         7

             umpire1          umpire2
0          Asad Rauf      RE Koertzen
1          MR Benson       SL Shastri
2          Aleem Dar   GA Pratapkumar
3           SJ Davis        DJ Harper
4          BF Bowden      K Hariharan
..               ...              ...
572   A Nand Kishore     BNJ Oxenford
573     AK Chaudhary  HDPK Dharmasena
574        M Erasmus    C Shamshuddin
575        M Erasmus        CK Nandan
576  HDPK Dharmasena     BNJ Oxenford

[577 rows x 19 columns]>

In [19]:
a.isna()

,match_id,season,city,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,player_of_match_id,venue,venue_id,umpire1,umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
573,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
574,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
575,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
576,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [20]:
a.isna().any()

match_id              False
season                False
city                   True
date                  False
team1_id              False
team2_id              False
toss_winner           False
toss_decision         False
result                False
dl_applied            False
winner                 True
win_by_runs           False
win_by_wickets        False
player_of_match        True
player_of_match_id     True
venue                 False
venue_id              False
umpire1               False
umpire2               False
dtype: bool

In [21]:
a.isna().sum()

match_id              0
season                0
city                  7
date                  0
team1_id              0
team2_id              0
toss_winner           0
toss_decision         0
result                0
dl_applied            0
winner                3
win_by_runs           0
win_by_wickets        0
player_of_match       3
player_of_match_id    3
venue                 0
venue_id              0
umpire1               0
umpire2               0
dtype: int64

In [27]:
a.shape

(577, 18)

In [28]:
del a['winner']

In [29]:
del a['player_of_match']

In [30]:
del a['player_of_match_id']

In [31]:
a.shape

(577, 15)

In [32]:
print(a.head())

  match_id  season        date team1_id team2_id toss_winner toss_decision  \
0   2008_1    2008  18-04-2008      KKR      RCB         RCB         field
1   2008_2    2008  19-04-2008      CSK      KXI         CSK           bat
2   2008_3    2008  19-04-2008       RR       DD          RR           bat
3   2008_4    2008  20-04-2008       MI      RCB          MI           bat
4   2008_5    2008  20-04-2008       DC      KKR          DC           bat

   result  dl_applied  win_by_runs  win_by_wickets  \
0  normal           0          140               0
1  normal           0           33               0
2  normal           0            0               9
3  normal           0            0               5
4  normal           0            0               5

                                               venue  venue_id    umpire1  \
0         M.Chinnaswamy Stadium Bengaluru, Karnataka         7  Asad Rauf
1  I.S. Bindra Punjab Cricket Association Stadium...         9  MR Benson
2                    Feroz Shah Kotla Stadium, Delhi         2  Aleem Dar
3              Wankhede Stadium, Mumbai, Maharashtra         1   SJ Davis
4          Eden Garden Stadium, Kolkata, West Bengal         3  BF Bowden

          umpire2
0     RE Koertzen
1      SL Shastri
2  GA Pratapkumar
3       DJ Harper
4     K Hariharan

In [33]:
a.isna().any()

match_id          False
season            False
date              False
team1_id          False
team2_id          False
toss_winner       False
toss_decision     False
result            False
dl_applied        False
win_by_runs       False
win_by_wickets    False
venue             False
venue_id          False
umpire1           False
umpire2           False
dtype: bool

In [52]:
a.axes

[RangeIndex(start=0, stop=577, step=1),
 Index(['match_id', 'season', 'date', 'team1_id', 'team2_id', 'toss_winner',
        'toss_decision', 'result', 'dl_applied', 'win_by_runs',
        'win_by_wickets', 'venue', 'venue_id', 'umpire1', 'umpire2'],
       dtype='object')]

In [53]:
a.values

array([['2008_1', 2008, '18-04-2008', ..., 7, 'Asad Rauf', 'RE Koertzen'],
       ['2008_2', 2008, '19-04-2008', ..., 9, 'MR Benson', 'SL Shastri'],
       ['2008_3', 2008, '19-04-2008', ..., 2, 'Aleem Dar',
        'GA Pratapkumar'],
       ...,
       ['2016_58', 2016, '25-05-2016', ..., 2, 'M Erasmus',
        'C Shamshuddin'],
       ['2016_59', 2016, '27-05-2016', ..., 2, 'M Erasmus', 'CK Nandan'],
       ['2016_60', 2016, '29-05-2016', ..., 7, 'HDPK Dharmasena',
        'BNJ Oxenford']], dtype=object)

In [54]:
a.sum()

match_id          2008_12008_22008_32008_42008_52008_62008_72008...
season                                                      1160941
date              18-04-200819-04-200819-04-200820-04-200820-04-...
team1_id          KKRCSKRRMIDCKXIDCCSKDCKXIRCBKKRMIDDCSKKKRDDDCR...
team2_id          RCBKXIDDRCBKKRRRDDMIRRMIRRCSKDCKXIRCBMIRCBKXIK...
toss_winner       RCBCSKRRMIDCKXIDCMIRRMIRRKKRDCDDCSKKKRRCBKXIRR...
toss_decision     fieldbatbatbatbatbatbatfieldfieldfieldfieldbat...
result            normalnormalnormalnormalnormalnormalnormalnorm...
dl_applied                                                       15
win_by_runs                                                    7914
win_by_wickets                                                 1941
venue             M.Chinnaswamy Stadium Bengaluru, KarnatakaI.S....
venue_id                                                       5826
umpire1           Asad RaufMR BensonAleem DarSJ DavisBF BowdenAl...
umpire2           RE KoertzenSL ShastriGA PratapkumarDJ HarperK ...
dtype: object

In [55]:
a.count()

match_id          577
season            577
date              577
team1_id          577
team2_id          577
toss_winner       577
toss_decision     577
result            577
dl_applied        577
win_by_runs       577
win_by_wickets    577
venue             577
venue_id          577
umpire1           577
umpire2           577
dtype: int64

In [56]:
a.mean()

match_id                  inf
season            2012.029463
dl_applied           0.025997
win_by_runs         13.715771
win_by_wickets       3.363951
venue_id            10.097054
dtype: float64

In [57]:
a.std()

season             2.486247
dl_applied         0.159263
win_by_runs       23.619282
win_by_wickets     3.416049
venue_id           9.048535
dtype: float64

In [58]:
a.median()

match_id          201169.0
season              2012.0
dl_applied             0.0
win_by_runs            0.0
win_by_wickets         3.0
venue_id               7.0
dtype: float64

In [59]:
a.dropna()

,match_id,season,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,win_by_runs,win_by_wickets,venue,venue_id,umpire1,umpire2
0,2008_1,2008,18-04-2008,KKR,RCB,RCB,field,normal,0,140,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,19-04-2008,CSK,KXI,CSK,bat,normal,0,33,0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008_3,2008,19-04-2008,RR,DD,RR,bat,normal,0,0,9,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008_4,2008,20-04-2008,MI,RCB,MI,bat,normal,0,0,5,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008_5,2008,20-04-2008,DC,KKR,DC,bat,normal,0,0,5,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,2016_56,2016,22-05-2016,DD,RCB,RCB,field,normal,0,0,6,Shaheed Veer Narayan Singh International Stadium,27,A Nand Kishore,BNJ Oxenford
573,2016_57,2016,24-05-2016,GL,RCB,RCB,field,normal,0,0,4,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,HDPK Dharmasena
574,2016_58,2016,25-05-2016,SRH,KKR,KKR,field,normal,0,22,0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,C Shamshuddin
575,2016_59,2016,27-05-2016,GL,SRH,SRH,field,normal,0,0,4,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,CK Nandan
576,2016_60,2016,29-05-2016,SRH,RCB,SRH,bat,normal,0,8,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,HDPK Dharmasena,BNJ Oxenford

In [61]:
a.dropna(how="all")

,match_id,season,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,win_by_runs,win_by_wickets,venue,venue_id,umpire1,umpire2
0,2008_1,2008,18-04-2008,KKR,RCB,RCB,field,normal,0,140,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,19-04-2008,CSK,KXI,CSK,bat,normal,0,33,0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008_3,2008,19-04-2008,RR,DD,RR,bat,normal,0,0,9,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008_4,2008,20-04-2008,MI,RCB,MI,bat,normal,0,0,5,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008_5,2008,20-04-2008,DC,KKR,DC,bat,normal,0,0,5,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,2016_56,2016,22-05-2016,DD,RCB,RCB,field,normal,0,0,6,Shaheed Veer Narayan Singh International Stadium,27,A Nand Kishore,BNJ Oxenford
573,2016_57,2016,24-05-2016,GL,RCB,RCB,field,normal,0,0,4,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,HDPK Dharmasena
574,2016_58,2016,25-05-2016,SRH,KKR,KKR,field,normal,0,22,0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,C Shamshuddin
575,2016_59,2016,27-05-2016,GL,SRH,SRH,field,normal,0,0,4,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,CK Nandan
576,2016_60,2016,29-05-2016,SRH,RCB,SRH,bat,normal,0,8,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,HDPK Dharmasena,BNJ Oxenford

In [62]:
a.dropna(axis=1)

,match_id,season,date,team1_id,team2_id,toss_winner,toss_decision,result,dl_applied,win_by_runs,win_by_wickets,venue,venue_id,umpire1,umpire2
0,2008_1,2008,18-04-2008,KKR,RCB,RCB,field,normal,0,140,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,Asad Rauf,RE Koertzen
1,2008_2,2008,19-04-2008,CSK,KXI,CSK,bat,normal,0,33,0,I.S. Bindra Punjab Cricket Association Stadium...,9,MR Benson,SL Shastri
2,2008_3,2008,19-04-2008,RR,DD,RR,bat,normal,0,0,9,"Feroz Shah Kotla Stadium, Delhi",2,Aleem Dar,GA Pratapkumar
3,2008_4,2008,20-04-2008,MI,RCB,MI,bat,normal,0,0,5,"Wankhede Stadium, Mumbai, Maharashtra",1,SJ Davis,DJ Harper
4,2008_5,2008,20-04-2008,DC,KKR,DC,bat,normal,0,0,5,"Eden Garden Stadium, Kolkata, West Bengal",3,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,2016_56,2016,22-05-2016,DD,RCB,RCB,field,normal,0,0,6,Shaheed Veer Narayan Singh International Stadium,27,A Nand Kishore,BNJ Oxenford
573,2016_57,2016,24-05-2016,GL,RCB,RCB,field,normal,0,0,4,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,AK Chaudhary,HDPK Dharmasena
574,2016_58,2016,25-05-2016,SRH,KKR,KKR,field,normal,0,22,0,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,C Shamshuddin
575,2016_59,2016,27-05-2016,GL,SRH,SRH,field,normal,0,0,4,"Feroz Shah Kotla Stadium, Delhi",2,M Erasmus,CK Nandan
576,2016_60,2016,29-05-2016,SRH,RCB,SRH,bat,normal,0,8,0,"M.Chinnaswamy Stadium Bengaluru, Karnataka",7,HDPK Dharmasena,BNJ Oxenford

In [40]:
from statistics import mean,median,mode,variance

In [35]:
print(mean(a['season']))

2012.0294627383016

In [36]:
print(median(a['dl_applied']))

0

In [37]:
print(mode(a['win_by_runs']))

0

In [41]:
print(variance(a['win_by_wickets']))

11.6693926920855

In [43]:
b=a['win_by_runs']

In [44]:
b

0      140
1       33
2        0
3        0
4        0
      ...
572      0
573      0
574     22
575      0
576      8
Name: win_by_runs, Length: 577, dtype: int64

In [45]:
b.max()

144

In [46]:
b.min()

0

In [47]:
b.cumsum()

0       140
1       173
2       173
3       173
4       173
       ...
572    7884
573    7884
574    7906
575    7906
576    7914
Name: win_by_runs, Length: 577, dtype: int64

In [48]:
b.cumprod()

0       140
1      4620
2         0
3         0
4         0
       ...
572       0
573       0
574       0
575       0
576       0
Name: win_by_runs, Length: 577, dtype: int64

In [49]:
b.count()

577

In [50]:
a.T

,0,1,2,3,4,5,6,7,8,9,...,567,568,569,570,571,572,573,574,575,576
match_id,2008_1,2008_2,2008_3,2008_4,2008_5,2008_6,2008_7,2008_8,2008_9,2008_10,...,2016_51,2016_52,2016_53,2016_54,2016_55,2016_56,2016_57,2016_58,2016_59,2016_60
season,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,...,2016,2016,2016,2016,2016,2016,2016,2016,2016,2016
date,18-04-2008,19-04-2008,19-04-2008,20-04-2008,20-04-2008,21-04-2008,22-04-2008,23-04-2008,24-04-2008,25-04-2008,...,19-05-2016,20-05-2016,21-05-2016,21-05-2016,22-05-2016,22-05-2016,24-05-2016,25-05-2016,27-05-2016,29-05-2016
team1_id,KKR,CSK,RR,MI,DC,KXI,DC,CSK,DC,KXI,...,KKR,SRH,KXI,MI,KKR,DD,GL,SRH,GL,SRH
team2_id,RCB,KXI,DD,RCB,KKR,RR,DD,MI,RR,MI,...,GL,DD,RPS,GL,SRH,RCB,RCB,KKR,SRH,RCB
toss_winner,RCB,CSK,RR,MI,DC,KXI,DC,MI,RR,MI,...,GL,DD,KXI,GL,SRH,RCB,RCB,KKR,SRH,SRH
toss_decision,field,bat,bat,bat,bat,bat,bat,field,field,field,...,field,field,bat,field,field,field,field,field,field,bat
result,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal,...,normal,normal,normal,normal,normal,normal,normal,normal,normal,normal
dl_applied,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
win_by_runs,140,33,0,0,0,0,0,6,0,66,...,0,0,0,0,22,0,0,22,0,8
win_by_wickets,0,0,9,5,5,6,9,0,3,0,...,6,6,4,6,0,6,4,0,4,0
venue,"M.Chinnaswamy Stadium Bengaluru, Karnataka",I.S. Bindra Punjab Cricket Association Stadium...,"Feroz Shah Kotla Stadium, Delhi","Wankhede Stadium, Mumbai, Maharashtra","Eden Garden Stadium, Kolkata, West Bengal","Sawai Man Singh Stadium, Jaipur, Rajasthan","Rajiv Gandhi International Stadium, Hyderabad","M.A.Chidambaram Stadium Chennai, Tamil Nadu","Rajiv Gandhi International Stadium, Hyderabad",I.S. Bindra Punjab Cricket Association Stadium...,...,Green Park,Shaheed Veer Narayan Singh International Stadium,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Green Park,"Eden Garden Stadium, Kolkata, West Bengal",Shaheed Veer Narayan Singh International Stadium,"M.Chinnaswamy Stadium Bengaluru, Karnataka","Feroz Shah Kotla Stadium, Delhi","Feroz Shah Kotla Stadium, Delhi","M.Chinnaswamy Stadium Bengaluru, Karnataka"
venue_id,7,9,2,1,3,6,4,5,4,9,...,34,27,25,34,3,27,7,2,2,7
umpire1,Asad Rauf,MR Benson,Aleem Dar,SJ Davis,BF Bowden,Aleem Dar,IL Howell,DJ Harper,Asad Rauf,Aleem Dar,...,AK Chaudhary,A Nand Kishore,HDPK Dharmasena,AK Chaudhary,KN Ananthapadmanabhan,A Nand Kishore,AK Chaudhary,M Erasmus,M Erasmus,HDPK Dharmasena
umpire2,RE Koertzen,SL Shastri,GA Pratapkumar,DJ Harper,K Hariharan,RB Tiffin,AM Saheba,GA Pratapkumar,MR Benson,AM Saheba,...,CK Nandan,BNJ Oxenford,Nitin Menon,CK Nandan,M Erasmus,BNJ Oxenford,HDPK Dharmasena,C Shamshuddin,CK Nandan,BNJ Oxenford

In [51]:
b.T

0      140
1       33
2        0
3        0
4        0
      ...
572      0
573      0
574     22
575      0
576      8
Name: win_by_runs, Length: 577, dtype: int64